# get heights for people:
```{r}
# one thousand individuals
set.seed(1)
heights = rnorm(1000, mean = 170, sd = 8)
p = 0.995
q = 0.005
aa = p^2
tt = q^2
at = 2*p*q
aa + tt + at
gts = sample(0:2, size = 1000, replace = T, prob = c(aa, at, tt))

df = data.frame(samples = 1:1000, gts = gts, heights = heights)
effect = 1 # everyone gets 1 extra cm for each T allele they have

df$heightadd = df$gts * effect

error = rnorm(1000, mean = 0, sd = 3)
df$full_height = df$heights + df$heightadd + error

library(ggplot2)
ggplot(df, aes(gts, full_height)) + geom_point() + xlab('Number of "T" alleles on chromosome 1, position 200') + ylab('Height in cm') + scale_x_continuous(breaks=c(0, 1, 2)) + geom_smooth(method = 'lm', se = F) + ggtitle('P-value = 0.114') + stat_summary(fun.data = give.n, geom = 'text')

lm(full_height ~ gts, data = df) %>% summary

ggplot(df, aes(gts, full_height)) + geom_point() + xlab('Number of "A" alleles on chromosome 1, position 223') + ylab('Height in cm') + geom_smooth(method = 'lm') + scale_x_continuous(breaks=c(0, 1, 2))
```

# logistic
```{r}
dis.0 = 10
dis.1 = 50
dis.2 = 100
disease = rbind(data.frame(alleles = rep(0, dis.0), disease = rep(1, dis.0)), data.frame(alleles = rep(1, dis.1), disease = rep(1, dis.1)), data.frame(alleles = rep(2, dis.2), disease = rep(1, dis.2)))

# Individuals without disease
# nodis.0 = input$nodisease_0
# nodis.1 = input$nodisease_1
# nodis.2 = input$nodisease_2

nodis.0 = 100 
nodis.1 = 50
nodis.2 = 10
nodisease = rbind(data.frame(alleles = rep(0, nodis.0), disease = rep(0, nodis.0)), data.frame(alleles = rep(1, nodis.1), disease = rep(0, nodis.1)), data.frame(alleles = rep(2, nodis.2), disease = rep(0, nodis.2)))

df = rbind(disease, nodisease)
df$ID = sample(1:nrow(df))
df = dplyr::select(df, ID, alleles, disease)
df = df[order(df$ID),]

binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}

ggplot(df, aes(alleles, disease)) + geom_jitter(width = 0.05, height = 0.05) + binomial_smooth() + xlab('Number of "T" alleles on chromosome 1, position 200') + ylab('Type 2 diabetes status') + scale_x_continuous(breaks=c(0, 1, 2)) + scale_y_continuous(breaks=c(0, 1))
```
